name: partB_flow

# learning hyperparameters
batch_size: 128
epochs: 100
lr: 0.001

#Model
model: MNISTFlow
num_transformations: 14
num_hidden: 256
masking: checkerboard


# Data
dim: 784
transform_description: dequantized

