batch_size: 128
config: src/configs/partB_VAE.yaml
decoder: ContinuesBernoulliDecoder
device: cpu
dim: 784
encoder: GaussianEncoder
encoder_decoder_nets: LinearEncoderDecoderNets
epochs: 5
latent_dim: 2
lr: 0.001
model: VAE
name: partB_VAE_test_version
prior: VampPrior
seed: 42
transform_description: flatten
version: test_version
