batch_size: 128
config: src/configs/partA_FlowPrior.yaml
decoder: BernoulliDecoder
device: cuda
encoder: GaussianEncoder
encoder_decoder_nets: LinearEncoderDecoderNets
epochs: 20
latent_dim: 2
lr: 0.001
model: VAE
name: partA_flow_v1
prior: FlowPrior
seed: 1113
transform_description: binarized
version: v1
