batch_size: 128
config: src/configs/partA_VampPrior.yaml
decoder: BernoulliDecoder
device: cuda
encoder: GaussianEncoder
encoder_decoder_nets: LinearEncoderDecoderNets
epochs: 20
latent_dim: 2
lr: 0.001
model: VAE
name: partA_vampPrior_v1
prior: VampPrior
seed: 789
transform_description: binarized
version: v1
