T: 1000
batch_size: 128
beta_1: 0.0001
beta_T: 0.02
config: AMLsrc/configs/partB_DDPM.yaml
device: cuda
dim: 784
epochs: 100
lr: 0.001
model: DDPM
name: partB_ddpm_v1
network: Unet
seed: 42
transform_description: minus_one_to_one
version: v1
