batch_size: 128
config: AMLsrc/configs/partB_Flow.yaml
device: cuda
dim: 784
epochs: 100
lr: 0.001
masking: checkerboard
model: MNISTFlow
name: partB_flow_v1
num_hidden: 256
num_transformations: 14
seed: 42
transform_description: dequantized
version: v1
